# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Map 8-digit CUSIP to 9-digit CUSIP
#'
#' This function computes the check digit and adds it to the 8-digit CUSIP.
#'
#' @param cusip8 A character vector of 8-digit CUSIPs.
#'
#' @export
cusip8_to_cusip9 <- function(cusip8) {
    .Call(`_barketools_cusip8_to_cusip9`, cusip8)
}

